# Generated by Django 5.2 on 2026-05-04 09:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Login attempt', 'verbose_name_plural': 'Login attempts'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_active'], 'verbose_name': 'User session', 'verbose_name_plural': 'User sessions'},
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='token',
            field=models.CharField(default=accounts.models._generate_otp, editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_initials',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
    ]
