# Generated by Django 5.2 on 2026-03-12 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_temp_c', models.DecimalField(decimal_places=1, help_text='Minimum water temperature (°C)', max_digits=4)),
                ('max_temp_c', models.DecimalField(decimal_places=1, help_text='Maximum water temperature (°C)', max_digits=4)),
                ('feeding_rate_pct', models.DecimalField(decimal_places=2, help_text='Daily feed as % of biomass', max_digits=4)),
            ],
            options={
                'ordering': ['min_temp_c'],
            },
        ),
        migrations.CreateModel(
            name='FishBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('tilapia', 'Tilapia'), ('catfish', 'Catfish'), ('carp', 'Carp'), ('other', 'Other')], max_length=50)),
                ('stocking_date', models.DateField()),
                ('initial_count', models.PositiveIntegerField()),
                ('initial_avg_weight_g', models.DecimalField(decimal_places=2, help_text='Average weight per fish at stocking (grams)', max_digits=6)),
                ('target_harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('area_m2', models.DecimalField(decimal_places=2, help_text='Surface area in square meters', max_digits=8)),
                ('max_depth_m', models.DecimalField(decimal_places=2, help_text='Maximum depth in meters', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_amount_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('auto_calculated', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='farm.fishbatch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('message', models.CharField(default='Time to feed this batch.', max_length=255)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_reminders', to='farm.fishbatch')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddField(
            model_name='fishbatch',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='farm.pond'),
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('water_temp_c', models.DecimalField(decimal_places=1, help_text='Water temperature (°C)', max_digits=4)),
                ('dissolved_oxygen_mg_l', models.DecimalField(decimal_places=2, help_text='Dissolved oxygen (mg/L)', max_digits=4)),
                ('ph', models.DecimalField(decimal_places=2, help_text='Water pH', max_digits=4)),
                ('rainfall_mm', models.DecimalField(decimal_places=2, default=0, help_text='Rainfall (mm)', max_digits=6)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='farm.pond')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('surviving_count', models.PositiveIntegerField()),
                ('avg_weight_g', models.DecimalField(decimal_places=2, help_text='Average weight per fish (grams)', max_digits=7)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='farm.fishbatch')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
