# Generated by Django 5.2 on 2026-03-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('condition', models.CharField(max_length=50)),
                ('feed_percent', models.DecimalField(decimal_places=2, help_text='Recommended feed percentage based on ambient weather', max_digits=5)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
