# Generated by Django 5.2 on 2026-03-27 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_dailyweather'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('oxygen', 'Dissolved Oxygen'), ('ph', 'pH')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='iot', max_length=50)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='farm.pond')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
