# Generated by Django 5.2 on 2026-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_sensorreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweather',
            name='location_query',
            field=models.CharField(default='', max_length=100),
        ),
    ]
