# Generated by Django 5.2 on 2026-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_farmprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('auto', 'Auto (Air Temp Estimate)'), ('sensor', 'IoT Sensor')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='district',
            field=models.CharField(blank=True, help_text='Bangladesh district (fallback when GPS denied)', max_length=60),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='farming_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of fish farming experience', null=True),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude (auto-detected or entered manually)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude (auto-detected or entered manually)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False, help_text='True once the user finishes all 4 onboarding steps'),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='species',
            field=models.JSONField(blank=True, default=list, help_text='List of farmed species, e.g. ["tilapia","rui"]'),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='upazila',
            field=models.CharField(blank=True, help_text='Bangladesh upazila', max_length=60),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='weather_condition',
            field=models.CharField(blank=True, help_text='e.g. "Clear", "Rain"', max_length=60),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='weather_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the cached weather was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='weather_humidity_pct',
            field=models.PositiveIntegerField(blank=True, help_text='Last fetched relative humidity (%)', null=True),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='weather_rain_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rain volume in last 1h (mm) — 0 means no rain', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='weather_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last fetched air temperature (°C) at farm location', max_digits=5, null=True),
        ),
    ]
