# Generated by Django 5.2 on 2026-04-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_pond_owner_per_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=200)),
                ('started_at', models.CharField(max_length=40)),
                ('finished_at', models.CharField(max_length=40)),
                ('total_operations', models.IntegerField(default=0)),
                ('aggregated_results', models.JSONField(default=dict, help_text='Per-operation aggregated stats')),
                ('system_info', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Benchmark Run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, help_text='View function name', max_length=100)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('elapsed_ms', models.FloatField(help_text='Total response time (ms)')),
                ('memory_before_mb', models.FloatField(default=0.0)),
                ('memory_after_mb', models.FloatField(default=0.0)),
                ('db_query_count', models.IntegerField(default=0)),
                ('db_query_time_ms', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Performance Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
