# Generated by Django 5.2 on 2026-04-30 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_benchmarkrun_performancelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('species', models.CharField(default='General', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], default='low', max_length=10)),
                ('ai_response', models.TextField(help_text='Full AI diagnosis text')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(blank=True, help_text='Optional — which pond this disease was detected in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_logs', to='farm.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_alerts', to='farm.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'disease_name')},
            },
        ),
    ]
