# Generated by Django 5.2 on 2026-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_diseaselog_diseasealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('feed', 'Feed'), ('transport', 'Transport'), ('doctor', 'Veterinarian / Doctor'), ('medicine', 'Medicine / Treatment'), ('labour', 'Labour'), ('equipment', 'Equipment'), ('electricity', 'Electricity'), ('fingerlings', 'Fingerlings / Stocking'), ('other', 'Other')], max_length=20),
        ),
    ]
