# Generated by Django 5.2 on 2026-06-10 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('nid', models.CharField(blank=True, help_text='National ID number', max_length=20)),
                ('role', models.CharField(choices=[('manager', 'Farm Manager'), ('feeder', 'Fish Feeder'), ('guard', 'Security Guard'), ('cleaner', 'Pond Cleaner'), ('technician', 'Equipment Technician'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=10)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('monthly_salary', models.DecimalField(decimal_places=2, help_text='Monthly salary (BDT)', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_ponds', models.ManyToManyField(blank=True, help_text='Which ponds this worker is responsible for (if any)', related_name='workers', to='farm.pond')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='farm.farmprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Payment month (YYYY-MM-01)')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], default='pending', max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='farm.worker')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('worker', 'month')},
            },
        ),
    ]
