"""
farm/management/commands/evaluate_feed_recommendation.py
─────────────────────────────────────────────────────────────────────────────
Evaluates the effectiveness of the Smart Feed Calculator
(farm/services/feed_calculator.py) — supervisor feedback point #5.

feed_calculator.py is a DETERMINISTIC FORMULA, not a trained model, so
"evaluation" here means something different from the ML modules:

  A. SENSITIVITY / CONSISTENCY CHECK (always runs, no data needed)
     Sweeps biomass and water-temperature ranges through the exact
     production formula (_get_cached_profile_rate, _temperature_factor)
     and verifies expected monotonic behaviour (e.g. feed should never
     decrease when biomass increases at fixed temperature).

  B. REAL-FARM-DATA CHECK (runs only if data exists)
     For any FishBatch with farmer-adjusted FeedLog entries
     (auto_calculated=False — i.e. the farmer overrode the system's
     number), compares the system's recommendation for that exact date
     against what the farmer actually fed. Comparing against
     auto_calculated=True logs would be circular (they WERE generated by
     this formula), so only manual overrides are meaningful ground truth.
     Also computes realized FCR per batch from real GrowthRecord + FeedLog
     history, for comparison against literature FCR ranges.

  C. LITERATURE-BENCHMARKED SIMULATION (always runs — the main result if
     the farm has little real data yet, which is expected for an early-
     stage student project)
     Simulates one full grow-out cycle (180 days) using a representative
     tilapia growth curve and a representative Bangladesh seasonal water
     temperature profile, runs the ACTUAL production feeding formula
     day-by-day, and compares the resulting implied FCR (total feed /
     total weight gain) against literature FCR ranges for tilapia
     (~1.2–2.0, commonly ~1.7–2.0 in Bangladesh pond studies).

     NOTE: the growth curve and temperature profile are illustrative
     assumptions (documented inline below), not measured data. Replace
     GROWTH_CURVE_G / TEMP_PROFILE_C with real observed values if/when
     you have a full season of real pond data, for a stronger paper claim.

OUTPUTS
-------
  - results/feed_eval_sensitivity_<ts>.csv     (sensitivity sweep table)
  - results/feed_eval_simulation_<ts>.csv      (day-by-day simulated feeding)
  - results/feed_eval_report_<ts>.md           (paper-ready summary)

USAGE
-----
    python manage.py evaluate_feed_recommendation
    python manage.py evaluate_feed_recommendation --out-dir research/feed_recommendation_eval/results
"""
from __future__ import annotations

import csv
import math
from datetime import date, timedelta
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.utils import timezone

from farm.models import FishBatch, FeedLog, GrowthRecord
from farm.services.feed_calculator import (
    _get_cached_profile_rate,
    _temperature_factor,
    _size_factor,
    ensure_default_feeding_profiles,
    smart_feed_kg_for_batch,
)

# Literature benchmark (see report "Sources" section for citations)
LITERATURE_FCR_MIN = 1.2
LITERATURE_FCR_MAX = 2.0
LITERATURE_FCR_TYPICAL_BD_TILAPIA = (1.70, 1.97)  # Bangladesh pond/tank studies range

# ── Illustrative simulation inputs (see module docstring — replace with real
#    observed data when available) ──────────────────────────────────────────
SIM_DAYS = 180
SIM_INITIAL_COUNT = 1000
SIM_SURVIVAL_RATE_AT_HARVEST = 0.90  # linear die-off assumption
# (day, weight_g) control points for a typical tilapia grow-out curve;
# linearly interpolated between points.
GROWTH_CURVE_G = [(0, 5), (30, 25), (60, 60), (90, 110), (120, 170), (150, 230), (180, 280)]
# Representative Bangladesh pond water-temperature seasonal approximation
# (sinusoidal: warmest ~Apr-May, coolest ~Jan), assuming stocking on day-of-year 90 (~April 1).
SIM_STOCKING_DOY = 90


class Command(BaseCommand):
    help = "Evaluate the Smart Feed Calculator against real farm data and a literature-benchmarked simulation."

    def add_arguments(self, parser):
        parser.add_argument("--out-dir", type=str, default=None)

    def handle(self, *args, **opts):
        out_dir = Path(opts["out_dir"]) if opts["out_dir"] else (
            Path(settings.BASE_DIR) / "research" / "feed_recommendation_eval" / "results"
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        ts = timezone.now().strftime("%Y%m%d_%H%M%S")

        ensure_default_feeding_profiles()

        sensitivity_rows = self._run_sensitivity_check()
        real_data = self._run_real_data_check()
        sim_rows, sim_summary = self._run_simulation()

        # ── Write CSVs ───────────────────────────────────────────────────────
        sens_csv = out_dir / f"feed_eval_sensitivity_{ts}.csv"
        with open(sens_csv, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=["biomass_kg", "water_temp_c", "avg_weight_g", "recommended_feed_kg", "feed_pct_of_biomass"])
            w.writeheader()
            w.writerows(sensitivity_rows)

        sim_csv = out_dir / f"feed_eval_simulation_{ts}.csv"
        with open(sim_csv, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=["day", "weight_g", "surviving_count", "biomass_kg", "water_temp_c", "feed_kg"])
            w.writeheader()
            w.writerows(sim_rows)

        report_path = out_dir / f"feed_eval_report_{ts}.md"
        self._write_report(report_path, sensitivity_rows, real_data, sim_summary)

        self.stdout.write(self.style.SUCCESS(f"[saved] {sens_csv}"))
        self.stdout.write(self.style.SUCCESS(f"[saved] {sim_csv}"))
        self.stdout.write(self.style.SUCCESS(f"[saved] {report_path}"))
        self.stdout.write(f"\nSimulated implied FCR: {sim_summary['implied_fcr']:.2f} "
                           f"(literature range: {LITERATURE_FCR_MIN}-{LITERATURE_FCR_MAX})")
        if real_data["batches_with_overrides"]:
            self.stdout.write(f"Real-data comparison: {real_data['n_comparisons']} farmer-override "
                               f"logs compared, mean abs diff {real_data['mean_abs_pct_diff']:.1f}%")
        else:
            self.stdout.write(self.style.WARNING(
                "No farmer-override FeedLog entries found yet — real-data comparison section "
                "will note this and rely on the simulation instead."
            ))

    # ── A. Sensitivity check ────────────────────────────────────────────────
    def _run_sensitivity_check(self):
        """Sweep biomass x temperature x fish-weight through the real formula; check monotonicity."""
        rows = []
        biomass_values = [1, 5, 10, 50, 100, 500, 1000]
        temp_values = [10, 15, 18, 20, 22, 24, 26, 28, 30, 32, 35, 38]
        weight_values = [3, 15, 35, 100, 250, 500]  # grams — representative fry-to-harvest sizes

        for temp in temp_values:
            rate_pct = _get_cached_profile_rate(temp)
            temp_factor = _temperature_factor(temp)
            for weight_g in weight_values:
                sz_factor = _size_factor(weight_g)
                for biomass in biomass_values:
                    if rate_pct is None:
                        continue
                    feed_kg = round(biomass * rate_pct / 100.0 * temp_factor * sz_factor, 3)
                    rows.append({
                        "biomass_kg": biomass, "water_temp_c": temp, "avg_weight_g": weight_g,
                        "recommended_feed_kg": feed_kg,
                        "feed_pct_of_biomass": round(feed_kg / biomass * 100, 2) if biomass else 0,
                    })

        violations = []
        # Check 1: at fixed (temp, weight), feed must strictly increase with biomass
        for temp in temp_values:
            for weight_g in weight_values:
                subset = sorted(
                    [r for r in rows if r["water_temp_c"] == temp and r["avg_weight_g"] == weight_g],
                    key=lambda r: r["biomass_kg"],
                )
                for a, b in zip(subset, subset[1:]):
                    if b["recommended_feed_kg"] <= a["recommended_feed_kg"]:
                        violations.append(("biomass", temp, weight_g, a["biomass_kg"], b["biomass_kg"]))

        # Check 2: at fixed (temp, biomass), feed % of biomass must NOT increase as fish get bigger
        for temp in temp_values:
            for biomass in biomass_values:
                subset = sorted(
                    [r for r in rows if r["water_temp_c"] == temp and r["biomass_kg"] == biomass],
                    key=lambda r: r["avg_weight_g"],
                )
                for a, b in zip(subset, subset[1:]):
                    if b["feed_pct_of_biomass"] > a["feed_pct_of_biomass"]:
                        violations.append(("size", temp, biomass, a["avg_weight_g"], b["avg_weight_g"]))

        self._sensitivity_violations = violations
        return rows

    # ── B. Real-data check ──────────────────────────────────────────────────
    def _run_real_data_check(self):
        result = {
            "batches_with_overrides": 0, "n_comparisons": 0,
            "mean_abs_pct_diff": 0.0, "per_batch_fcr": [],
        }
        diffs = []

        for batch in FishBatch.objects.all():
            override_logs = FeedLog.objects.filter(batch=batch, auto_calculated=False).order_by("date")
            if override_logs.exists():
                result["batches_with_overrides"] += 1
                for log in override_logs:
                    recommended = smart_feed_kg_for_batch(batch, day=log.date)
                    if recommended is None:
                        continue
                    actual = float(log.feed_amount_kg)
                    if actual <= 0:
                        continue
                    pct_diff = abs(recommended - actual) / actual * 100
                    diffs.append(pct_diff)
                    result["n_comparisons"] += 1

            # Realized FCR from real data (any batch with enough history)
            growth = list(GrowthRecord.objects.filter(batch=batch).order_by("date"))
            all_logs = FeedLog.objects.filter(batch=batch)
            if len(growth) >= 2 and all_logs.exists():
                first, last = growth[0], growth[-1]
                weight_gain_kg = (
                    last.surviving_count * float(last.avg_weight_g)
                    - first.surviving_count * float(first.avg_weight_g)
                ) / 1000.0
                total_feed_kg = sum(float(l.feed_amount_kg) for l in all_logs)
                if weight_gain_kg > 0:
                    fcr = total_feed_kg / weight_gain_kg
                    result["per_batch_fcr"].append((batch.id, str(batch), round(fcr, 2)))

        if diffs:
            result["mean_abs_pct_diff"] = sum(diffs) / len(diffs)
        return result

    # ── C. Literature-benchmarked simulation ────────────────────────────────
    def _weight_at_day(self, day: int) -> float:
        for (d0, w0), (d1, w1) in zip(GROWTH_CURVE_G, GROWTH_CURVE_G[1:]):
            if d0 <= day <= d1:
                t = (day - d0) / (d1 - d0) if d1 != d0 else 0
                return w0 + t * (w1 - w0)
        return GROWTH_CURVE_G[-1][1]

    def _temp_at_day(self, day: int) -> float:
        doy = (SIM_STOCKING_DOY + day) % 365
        # Warmest ~day 110 (mid-April/May), coolest ~day 290 (mid-Jan): amplitude tuned
        # to a representative Bangladesh pond range (~20°C winter low to ~32°C summer high).
        return 26 + 6 * math.sin(2 * math.pi * (doy - 110) / 365)

    def _run_simulation(self):
        rows = []
        total_feed_kg = 0.0
        for day in range(SIM_DAYS + 1):
            weight_g = self._weight_at_day(day)
            survival = 1.0 - (1.0 - SIM_SURVIVAL_RATE_AT_HARVEST) * (day / SIM_DAYS)
            surviving_count = round(SIM_INITIAL_COUNT * survival)
            biomass_kg = surviving_count * weight_g / 1000.0
            water_temp = round(self._temp_at_day(day), 1)

            rate_pct = _get_cached_profile_rate(water_temp)
            temp_factor = _temperature_factor(water_temp)
            sz_factor = _size_factor(weight_g)
            feed_kg = round(biomass_kg * (rate_pct or 0) / 100.0 * temp_factor * sz_factor, 3) if rate_pct else 0.0
            total_feed_kg += feed_kg

            rows.append({
                "day": day, "weight_g": round(weight_g, 1), "surviving_count": surviving_count,
                "biomass_kg": round(biomass_kg, 2), "water_temp_c": water_temp, "feed_kg": feed_kg,
            })

        initial_weight_g = GROWTH_CURVE_G[0][1]
        final_weight_g = GROWTH_CURVE_G[-1][1]
        final_count = round(SIM_INITIAL_COUNT * SIM_SURVIVAL_RATE_AT_HARVEST)
        weight_gain_kg = (final_count * final_weight_g - SIM_INITIAL_COUNT * initial_weight_g) / 1000.0
        implied_fcr = total_feed_kg / weight_gain_kg if weight_gain_kg > 0 else float("nan")

        summary = {
            "total_feed_kg": round(total_feed_kg, 1),
            "weight_gain_kg": round(weight_gain_kg, 1),
            "implied_fcr": implied_fcr,
            "final_count": final_count,
        }
        return rows, summary

    # ── Report ───────────────────────────────────────────────────────────────
    def _write_report(self, path, sensitivity_rows, real_data, sim_summary):
        with open(path, "w", encoding="utf-8") as f:
            f.write("# Smart Feed Calculator — Effectiveness Evaluation\n\n")
            f.write(f"**Run date:** {timezone.now().strftime('%Y-%m-%d %H:%M')}\n\n")
            f.write("Evaluates `farm/services/feed_calculator.py` (supervisor feedback point #5). "
                    "This is a deterministic formula (biomass × temperature-based feeding rate × "
                    "temperature appetite factor), not a trained model, so evaluation combines "
                    "(A) internal consistency checks, (B) comparison against real farmer-adjusted "
                    "feed logs where available, and (C) a literature-benchmarked simulation.\n\n")

            f.write("## A. Sensitivity / Consistency Check\n\n")
            f.write(f"Swept {len(sensitivity_rows)} (biomass, temperature, fish-weight) combinations "
                    f"through the real production formula, checking two properties:\n")
            f.write("1. Feed must strictly increase with biomass at fixed temperature/weight.\n")
            f.write("2. Feed as a % of biomass must not increase as fish get bigger, at fixed "
                    "temperature/biomass (the size-based adjustment should only ever reduce or "
                    "hold the rate, never raise it, as fish grow).\n\n")
            if self._sensitivity_violations:
                f.write(f"⚠️ **{len(self._sensitivity_violations)} violations found** — see CSV for "
                        f"details; worth investigating a `FeedingProfile`/size-band boundary bug.\n\n")
            else:
                f.write("✅ No violations — feed recommendation behaves consistently across biomass, "
                        "temperature, and fish size, as expected.\n\n")

            f.write("Sample of the sweep (full table in the CSV):\n\n")
            f.write("| Water Temp (°C) | Fish Weight (g) | Biomass (kg) | Recommended Feed (kg) | Feed % of Biomass |\n|---|---|---|---|---|\n")
            for r in sensitivity_rows[::23][:15]:
                f.write(f"| {r['water_temp_c']} | {r['avg_weight_g']} | {r['biomass_kg']} | {r['recommended_feed_kg']} | {r['feed_pct_of_biomass']}% |\n")

            f.write("\n## B. Real Farm Data Comparison\n\n")
            if real_data["batches_with_overrides"]:
                f.write(f"- Batches with at least one farmer-adjusted (manually overridden) feed log: "
                        f"{real_data['batches_with_overrides']}\n")
                f.write(f"- Total comparisons (system recommendation vs. what the farmer actually fed): "
                        f"{real_data['n_comparisons']}\n")
                f.write(f"- Mean absolute difference: **{real_data['mean_abs_pct_diff']:.1f}%**\n\n")
            else:
                f.write("No farmer-adjusted feed logs (`FeedLog.auto_calculated=False`) exist in the "
                        "database yet — this is expected for an early-stage deployment with limited "
                        "real usage history. Comparing against `auto_calculated=True` logs would be "
                        "circular, since those were generated by this same formula. As real farmers "
                        "start overriding recommendations, re-run this command to populate this "
                        "section with real evidence. Section C below provides a literature-grounded "
                        "result in the meantime.\n\n")

            if real_data["per_batch_fcr"]:
                f.write("### Realized FCR from real batch history\n\n")
                f.write("| Batch | Realized FCR |\n|---|---|\n")
                for _id, name, fcr in real_data["per_batch_fcr"]:
                    f.write(f"| {name} | {fcr} |\n")
                f.write(f"\nLiterature ideal range: {LITERATURE_FCR_MIN}–{LITERATURE_FCR_MAX}; "
                        f"typical Bangladesh tilapia pond studies: "
                        f"{LITERATURE_FCR_TYPICAL_BD_TILAPIA[0]}–{LITERATURE_FCR_TYPICAL_BD_TILAPIA[1]}.\n\n")
            else:
                f.write("*(No batches yet have both growth history and feed logs long enough to "
                        "compute a realized FCR.)*\n\n")

            f.write("## C. Literature-Benchmarked Simulation\n\n")
            f.write(f"Simulated a {SIM_DAYS}-day tilapia grow-out cycle using the production feeding "
                    f"formula against a representative growth curve and seasonal Bangladesh pond "
                    f"temperature profile (see module docstring for the exact assumptions — these "
                    f"are illustrative, not measured, data).\n\n")
            f.write(f"- Total simulated feed used: **{sim_summary['total_feed_kg']} kg**\n")
            f.write(f"- Total weight gain: **{sim_summary['weight_gain_kg']} kg** "
                    f"({SIM_INITIAL_COUNT} stocked → {sim_summary['final_count']} surviving)\n")
            f.write(f"- **Implied FCR: {sim_summary['implied_fcr']:.2f}**\n\n")

            in_range = LITERATURE_FCR_MIN <= sim_summary['implied_fcr'] <= LITERATURE_FCR_MAX
            in_bd_range = LITERATURE_FCR_TYPICAL_BD_TILAPIA[0] <= sim_summary['implied_fcr'] <= LITERATURE_FCR_TYPICAL_BD_TILAPIA[1]
            f.write(f"This falls {'within' if in_range else 'outside'} the general literature FCR "
                    f"range ({LITERATURE_FCR_MIN}–{LITERATURE_FCR_MAX}), and "
                    f"{'within' if in_bd_range else 'outside'} the typical range reported in "
                    f"Bangladesh tilapia pond studies "
                    f"({LITERATURE_FCR_TYPICAL_BD_TILAPIA[0]}–{LITERATURE_FCR_TYPICAL_BD_TILAPIA[1]}), "
                    f"suggesting the feeding formula's calibration is "
                    f"{'biologically plausible' if in_range else 'worth revisiting — consider adjusting FeedingProfile rates'}.\n\n")

            f.write("## Methodology note — size-based feeding adjustment\n\n")
            f.write("An earlier version of this formula scaled feed rate by **water temperature "
                    "only**. A first simulation run (documented in this project's evaluation "
                    "history) showed this over-fed fish once they grew past ~150g, producing an "
                    "implied FCR (~2.6) well outside the literature range. Aquaculture feeding-rate "
                    "guidance indicates feeding rate should decrease sharply as fish grow (e.g. "
                    "~15-20% BW/day for fry vs. ~1-3% BW/day near harvest size), independent of "
                    "temperature. A `_size_factor()` multiplier (see `feed_calculator.py`) was "
                    "added to address this — its effect on the simulated FCR is shown in Section C "
                    "above. The multiplier bands are an engineering approximation calibrated "
                    "against general feeding-rate guidance rather than a single peer-reviewed "
                    "table specific to this species/system; refining them further with real farm "
                    "data remains a reasonable direction for future work.\n\n")

            f.write("## Sources\n\n")
            f.write("- FAO. *On-farm feeding and feed management in aquaculture* — "
                    "temperature and body-mass jointly determine appropriate feeding rate.\n")
            f.write("- Rahman & Islam (2021), *Sinking Feed Efficiency in Growth Performance, "
                    "FCR and Yield of Tilapia*, Bangladesh Agricultural University — FCR "
                    "1.70–1.97 in Bangladesh pond/tank tilapia trials.\n")
            f.write("- General aquaculture industry guidance: ideal FCR range 1.2–2.0 "
                    "(lower is better feed efficiency).\n")